### ISSUE TITLE
Don't let customers try to add a certificate for dynos that do not support SNI

### ISSUE THREAD

**Issue by sbastn** [dnsimple/addon-heroku#9]
On the SSL certificate page, I am presented with 2 certificates that have already expired:

<img width="432" alt="screen shot 2016-11-29 at 12 16 52 pm" src="https://cloud.githubusercontent.com/assets/80610/20707927/df71bfaa-b62d-11e6-8073-f8e7819e5cb8.png">

If I select any of them, the application crashes. So don't show them 😄

**Comment by aeden** [comment]
Closed by 9c22677c87cfac7f9d9e833f9c04a622249d72a5
